import { useEffect, useState } from "react";
import { motion, useReducedMotion, type Transition } from "framer-motion";
import {
  SimulationControls,
  type SimulationSpeed,
} from "../../../../components/ui/SimulationControls";
import type { TraceableSimulationProps } from "../../../../lib/types";

type PageEvent = "hit" | "fault";
type ClockFrame = { page: number | null; refBit: boolean; justEvicted: boolean; justInserted: boolean; scannedThisStep: boolean };
type StepState = { access: number; frames: ClockFrame[]; clockHand: number; event: PageEvent; evicted: number | null; faultCount: number; hitCount: number; scanHistory: number[]; description: string; decisionReason: string };

const referenceString = [1, 2, 3, 4, 1, 2, 5, 1, 2, 3, 4, 5];
const frame = (page: number | null, refBit = false, justEvicted = false, justInserted = false, scannedThisStep = false): ClockFrame => ({ page, refBit, justEvicted, justInserted, scannedThisStep });

const steps: StepState[] = [
  { access: 1, frames: [frame(1, true, false, true, true), frame(null), frame(null)], clockHand: 1, event: "fault", evicted: null, faultCount: 1, hitCount: 0, scanHistory: [0], description: "Page 1 misses and enters the first empty clock frame.", decisionReason: "The hand starts at empty frame 0. Insert page 1 with R=1, then advance the hand to frame 1." },
  { access: 2, frames: [frame(1, true), frame(2, true, false, true, true), frame(null)], clockHand: 2, event: "fault", evicted: null, faultCount: 2, hitCount: 0, scanHistory: [1], description: "Page 2 fills the next empty frame.", decisionReason: "The hand points to empty frame 1, so page 2 enters with R=1 and the hand advances." },
  { access: 3, frames: [frame(1, true), frame(2, true), frame(3, true, false, true, true)], clockHand: 0, event: "fault", evicted: null, faultCount: 3, hitCount: 0, scanHistory: [2], description: "Page 3 fills the final empty frame.", decisionReason: "Frame 2 is empty. After inserting page 3 with R=1, the hand wraps back to frame 0." },
  { access: 4, frames: [frame(4, true, true, true, true), frame(2, false, false, false, true), frame(3, false, false, false, true)], clockHand: 1, event: "fault", evicted: 1, faultCount: 4, hitCount: 0, scanHistory: [0, 1, 2, 0], description: "Page 4 triggers a full sweep before the first eviction.", decisionReason: "Frames 0, 1, and 2 all have R=1, so each gets a second chance and is cleared to R=0. Returning to frame 0, page 1 is now evicted for page 4." },
  { access: 1, frames: [frame(4, true), frame(1, true, true, true, true), frame(3, false)], clockHand: 2, event: "fault", evicted: 2, faultCount: 5, hitCount: 0, scanHistory: [1], description: "Page 1 faults and replaces page 2.", decisionReason: "The hand points at frame 1. Page 2 has R=0, so it has no second chance and is replaced immediately." },
  { access: 2, frames: [frame(4, true), frame(1, true), frame(2, true, true, true, true)], clockHand: 0, event: "fault", evicted: 3, faultCount: 6, hitCount: 0, scanHistory: [2], description: "Page 2 faults and replaces page 3.", decisionReason: "Frame 2 contains page 3 with R=0. The hand evicts it, gives page 2 R=1, and wraps to frame 0." },
  { access: 5, frames: [frame(5, true, true, true, true), frame(1, false, false, false, true), frame(2, false, false, false, true)], clockHand: 1, event: "fault", evicted: 4, faultCount: 7, hitCount: 0, scanHistory: [0, 1, 2, 0], description: "Page 5 causes another complete second-chance sweep.", decisionReason: "Pages 4, 1, and 2 all have R=1, so Clock clears every bit while advancing. On its return to frame 0, page 4 has R=0 and is replaced by page 5." },
  { access: 1, frames: [frame(5, true), frame(1, true, false, false, true), frame(2, false)], clockHand: 1, event: "hit", evicted: null, faultCount: 7, hitCount: 1, scanHistory: [1], description: "Page 1 is found in frame 1.", decisionReason: "A hit never moves the hand. It simply sets page 1's reference bit back to R=1, recording recent use." },
  { access: 2, frames: [frame(5, true), frame(1, true), frame(2, true, false, false, true)], clockHand: 1, event: "hit", evicted: null, faultCount: 7, hitCount: 2, scanHistory: [2], description: "Page 2 is also a hit.", decisionReason: "Page 2 is resident, so its R bit becomes 1. The clock hand remains ready at frame 1 for the next fault." },
  { access: 3, frames: [frame(5, false, false, false, true), frame(3, true, true, true, true), frame(2, false, false, false, true)], clockHand: 2, event: "fault", evicted: 1, faultCount: 8, hitCount: 2, scanHistory: [1, 2, 0, 1], description: "Page 3 needs a sweep before finding page 1 as its victim.", decisionReason: "Starting at frame 1, pages 1, 2, and 5 all have R=1, so Clock clears them. Returning to frame 1 finds page 1 at R=0, so it is replaced." },
  { access: 4, frames: [frame(5, false), frame(3, true), frame(4, true, true, true, true)], clockHand: 0, event: "fault", evicted: 2, faultCount: 9, hitCount: 2, scanHistory: [2], description: "Page 4 replaces page 2 at the hand.", decisionReason: "The hand reaches frame 2, where page 2 already has R=0. It is the immediate Clock victim." },
  { access: 5, frames: [frame(5, true, false, false, true), frame(3, true), frame(4, true)], clockHand: 0, event: "hit", evicted: null, faultCount: 9, hitCount: 3, scanHistory: [0], description: "Page 5 is the final cache hit.", decisionReason: "Page 5 is resident in frame 0. Clock restores R=1 and leaves the hand in place because no replacement is needed." },
];

const positions = [{ x: 110, y: 30 }, { x: 179, y: 150 }, { x: 41, y: 150 }];

function ClockDial({ state, transition, reduceMotion }: { state: StepState; transition: Transition; reduceMotion: boolean | null }) {
  const hand = positions[state.clockHand];
  return <div className="rounded-xl border border-border bg-background/60 p-3"><div className="flex items-center justify-between gap-2"><div><h4 className="font-mono text-[0.66rem] uppercase tracking-[0.14em] text-muted">Clock dial</h4><p className="mt-1 text-xs text-muted">hand points to the next frame to check</p></div><span className="font-mono text-[0.62rem] text-warning">hand → F{state.clockHand}</span></div><svg viewBox="0 0 220 220" className="mx-auto mt-2 block w-full max-w-[17rem]" role="img" aria-label={`Clock hand points to frame ${state.clockHand}`}><circle cx="110" cy="110" r="80" fill="var(--surface)" stroke="var(--border)" strokeWidth="2" /><motion.line x1="110" y1="110" initial={false} animate={{ x2: hand.x, y2: hand.y }} transition={transition} stroke="var(--warning)" strokeWidth="2.5" strokeLinecap="round" /><circle cx="110" cy="110" r="5" fill="var(--warning)" />{state.frames.map((item, index) => { const point = positions[index]; const color = item.justEvicted ? "var(--error)" : item.justInserted ? "var(--accent-os)" : item.refBit ? "var(--accent-os)" : "var(--border)"; const background = item.justEvicted ? "color-mix(in oklab, var(--error) 14%, var(--surface))" : item.refBit ? "color-mix(in oklab, var(--accent-os) 16%, var(--surface))" : "var(--background)"; return <g key={index}>{item.scannedThisStep ? <motion.circle cx={point.x} cy={point.y} r="35" fill="none" stroke="var(--warning)" strokeWidth="1.5" initial={false} animate={reduceMotion ? { opacity: 0.9 } : { opacity: [0.35, 1, 0.35], scale: [0.92, 1.1, 0.92] }} transition={reduceMotion ? { duration: 0 } : { duration: 1.25, repeat: Infinity, ease: "easeInOut" }} style={{ transformOrigin: `${point.x}px ${point.y}px` }} /> : null}<motion.circle cx={point.x} cy={point.y} r="28" initial={false} animate={{ fill: background, stroke: color }} transition={transition} strokeWidth="2" /><text x={point.x} y={point.y - 3} textAnchor="middle" fill="var(--foreground)" className="font-mono text-[13px] font-bold">{item.page ?? "—"}</text><circle cx={point.x + 12} cy={point.y + 11} r="4" fill={item.refBit ? "var(--accent-os)" : "var(--surface)"} stroke="var(--accent-os)" strokeWidth="1.2" /><text x={point.x} y={point.y + 17} textAnchor="middle" fill="var(--foreground-muted)" className="font-mono text-[8px]">F{index}</text></g>; })}</svg></div>;
}

export default function ClockPageReplacementSimulation({ externalStep }: TraceableSimulationProps = {}) {
  const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false); const [speed, setSpeed] = useState<SimulationSpeed>(1); const reduceMotion = useReducedMotion();
  useEffect(() => { if (!playing || externalStep !== undefined) return undefined; const id = window.setInterval(() => { setStep((current) => { if (current >= steps.length - 1) { setPlaying(false); return current; } return current + 1; }); }, 900 / speed); return () => window.clearInterval(id); }, [externalStep, playing, speed]);
  const currentStep = Math.max(0, Math.min(steps.length - 1, externalStep ?? step)); const current = steps[currentStep]; const transition: Transition = reduceMotion ? { duration: 0 } : { type: "spring", stiffness: 280, damping: 24 }; const accessed = currentStep + 1; const faultRate = Math.round((current.faultCount / accessed) * 100);
  return <section aria-label="Clock page replacement simulation"><header className="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">Clock Page Replacement</h3><p className="mt-1 text-sm text-muted">Second-Chance Algorithm</p></div><span className="rounded-full border border-border bg-background px-3 py-1 font-mono text-xs text-muted">access {currentStep + 1}/{steps.length}</span></header>
    <div className="mb-5 flex gap-1.5 overflow-x-auto pb-1" aria-label="Page reference string">{referenceString.map((page, index) => <span key={`${page}-${index}`} className="rounded-lg border px-2.5 py-1.5 font-mono text-xs" style={{ borderColor: index === currentStep ? "var(--accent-os)" : "var(--border)", backgroundColor: index === currentStep ? "color-mix(in oklab, var(--accent-os) 15%, var(--surface))" : "var(--surface)", color: index === currentStep ? "var(--accent-os)" : "var(--foreground-muted)", opacity: index > currentStep ? 0.45 : index < currentStep ? 0.62 : 1 }}>{page}</span>)}</div>
    <div className="mb-5 flex flex-wrap gap-3"><Stat label="Faults" value={current.faultCount} color="var(--error)" /><Stat label="Hits" value={current.hitCount} color="var(--success)" /><Stat label="Fault rate" value={`${faultRate}%`} color="var(--accent-os)" /></div>
    <section className="rounded-2xl border border-border bg-surface/30 p-4 sm:p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-mono text-[0.62rem] uppercase tracking-[0.14em] text-muted">Current access</p><p className="mt-1 font-mono text-xl text-accent-os">page {current.access} · {current.event.toUpperCase()}</p></div>{current.evicted !== null ? <span className="rounded-full border border-error/40 bg-error/10 px-3 py-1.5 font-mono text-xs text-error">evicted page {current.evicted}</span> : null}</div><div className="mt-5 grid gap-5 lg:grid-cols-[minmax(0,0.95fr)_minmax(0,1.05fr)]"><ClockDial state={current} transition={transition} reduceMotion={reduceMotion} /><div className="grid gap-4 sm:grid-cols-3">{current.frames.map((item, index) => { const hit = current.event === "hit" && item.page === current.access; const color = item.justEvicted ? "var(--error)" : item.justInserted ? "var(--accent-os)" : hit ? "var(--success)" : "var(--border)"; const background = item.justEvicted ? "color-mix(in oklab, var(--error) 13%, var(--surface))" : item.justInserted ? "color-mix(in oklab, var(--accent-os) 15%, var(--surface))" : hit ? "color-mix(in oklab, var(--success) 12%, var(--surface))" : "var(--background)"; return <motion.article key={index} initial={false} animate={{ borderColor: color, backgroundColor: background, y: item.justInserted || hit ? -3 : 0 }} transition={transition} className="relative flex min-h-32 flex-col justify-between rounded-xl border p-4"><div className="flex justify-between gap-2"><span className="font-mono text-[0.62rem] text-muted">Frame {index}</span><span className="flex items-center gap-1 font-mono text-[0.58rem]" style={{ color: item.refBit ? "var(--accent-os)" : "var(--foreground-muted)" }}><i className={`h-2 w-2 rounded-full border ${item.refBit ? "border-accent-os bg-accent-os" : "border-border bg-surface"}`} />R={item.refBit ? 1 : 0}</span></div><strong className="font-mono text-3xl font-bold" style={{ color: item.page === null ? "var(--foreground-muted)" : color }}>{item.page ?? "—"}</strong><span className="font-mono text-[0.62rem]" style={{ color }}>{item.justEvicted ? "REPLACED" : item.justInserted ? "INSERTED" : hit ? "HIT" : item.page === null ? "EMPTY" : "resident"}</span></motion.article>; })}</div></div>
      <div className="mt-5 rounded-xl border border-accent-os/40 bg-accent-os/10 p-4"><p className="font-mono text-[0.62rem] font-bold uppercase tracking-[0.14em] text-accent-os">Why?</p><p className="mt-2 text-sm leading-relaxed text-foreground">{current.decisionReason}</p><p className="mt-3 font-mono text-[0.62rem] text-muted">scanned this access: {current.scanHistory.map((index) => `F${index}`).join(" → ")}</p></div><div className="mt-5 flex flex-wrap gap-4 border-t border-border pt-3 font-mono text-[0.62rem] text-muted"><span>R=1 gets a second chance and clears to 0</span><span>R=0 is replaced immediately</span></div>
    </section>
    <section className="mt-5" aria-label="Clock access history"><p className="mb-2 font-mono text-[0.64rem] uppercase tracking-[0.14em] text-muted">Access history</p><div className="grid grid-cols-4 gap-2 sm:grid-cols-6 lg:grid-cols-12">{steps.map((state, index) => { const active = index === currentStep; const classes = "min-h-12 rounded-lg border font-mono text-xs transition " + (active ? "border-accent-os bg-accent-os/15 text-accent-os" : state.event === "hit" ? "border-success/30 bg-success/5 text-success" : "border-error/30 bg-error/5 text-error"); const content = <><strong className="block">{state.access}</strong><small className="text-[0.55rem] uppercase">{state.event}</small></>; return externalStep === undefined ? <button key={index} type="button" onClick={() => { setStep(index); setPlaying(false); }} className={classes}>{content}</button> : <span key={index} className={classes}>{content}</span>; })}</div></section>
    {externalStep === undefined ? <SimulationControls isPlaying={playing} speed={speed} canStepBack={step > 0} canStepForward={step < steps.length - 1} onPlayPause={() => setPlaying((value) => !value)} onStepBack={() => setStep((value) => Math.max(0, value - 1))} onStepForward={() => setStep((value) => Math.min(steps.length - 1, value + 1))} onReset={() => { setStep(0); setPlaying(false); }} onSpeedChange={setSpeed} /> : null}
  </section>;
}

function Stat({ label, value, color }: { label: string; value: string | number; color: string }) { return <div className="flex min-w-24 flex-col items-center rounded-xl border border-border bg-surface/30 px-4 py-2.5"><span className="font-mono text-[0.6rem] uppercase tracking-[0.12em] text-muted">{label}</span><strong className="mt-0.5 font-mono text-lg" style={{ color }}>{value}</strong></div>; }
